# Generated by Django 2.1.2 on 2018-11-26 23:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('day', models.DateField(default=datetime.date.today)),
                ('log', models.TextField(default='Write about how you are feeling today.')),
            ],
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom', models.CharField(choices=[('Anxiety', 'Anxiety'), ('Depression', 'Depression')], max_length=10)),
                ('average_rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='day',
            name='symptom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Symptom'),
        ),
        migrations.AlterUniqueTogether(
            name='symptom',
            unique_together={('user', 'symptom')},
        ),
        migrations.AlterUniqueTogether(
            name='day',
            unique_together={('symptom', 'day')},
        ),
    ]
