# Generated by Django 2.1.2 on 2018-11-29 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='log',
            field=models.TextField(),
        ),
    ]
