# Generated by Django 2.1.2 on 2018-11-05 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daylog',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
