# Generated by Django 2.1.2 on 2018-11-28 01:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='symptom',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='symptom',
            name='user',
        ),
        migrations.AddField(
            model_name='day',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='day',
            name='log',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='day',
            name='symptom',
            field=models.CharField(choices=[('Anxiety', 'Anxiety'), ('Depression', 'Depression')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='day',
            unique_together={('user', 'symptom', 'day')},
        ),
        migrations.DeleteModel(
            name='Symptom',
        ),
    ]
