# Generated by Django 2.1.2 on 2018-11-29 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20181128_0103'),
        ('home', '0002_auto_20181129_2150'),
    ]

    operations = [
    ]
