version: 2
jobs:
  build:
    working_directory: ~/Allay/
    docker:
      - image: circleci/python:3.7.1 # every job must define an image for the docker executor and subsequent jobs may define a different image.
        environment:
          PIPENV_VENV_IN_PROJECT: true
          DATABASE_URL: postgresql://root@localhost/allay?sslmode=disable
      - image: circleci/postgres:10.5 # an example of how to specify a service container
      
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - run:
          command: |
            sudo apt-get install python3-pip
            pip3 install virtualenv --user 
            virtualenv -p python3 venv
      - run:
          command: |
            source venv/bin/activate
      - run:
          command: |
            pip install django
            pip3 install psycopg2 
            pip install unittest-xml-reporting
      - run: sudo apt-get update
      - run: sudo apt-get install postgresql-10.5
      - run:
          command: |
            psql -h 127.0.0.1 -U postgres -c "CREATE DATABASE allay;"
            psql -h 127.0.0.1 -U postgres -c "CREATE USER allayteam WITH PASSWORD 'raven99dog'; GRANT ALL PRIVILEGES ON DATABASE databasename TO username;"
      - run:
          command: |
            cd mysite
            python manage.py test
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1
      
