version: 2
jobs:
  build:
    working_directory: ~/Allay/
    docker:
      - image: circleci/python:3.7.1 # every job must define an image for the docker executor and subsequent jobs may define a different image.
      environment:
        TEST_DATABASE_URL: postgresql://root@localhost/circle_test
        
      - image: circleci/postgres:10.5 # an example of how to specify a service container
      
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - run: sudo apt-get update
      - run: sudo apt-get install postgresql-client-9.6
      - run: whoami
      - run: |
          psql \
          -d $TEST_DATABASE_URL \
          -c "CREATE TABLE test (name char(25));"
      - run: |
          psql \
          -d $TEST_DATABASE_URL \
          -c "INSERT INTO test VALUES ('John'), ('Joanna'), ('Jennifer');"
      - run: |
          psql \
          -d $TEST_DATABASE_URL \
          -c "SELECT * from test"
      - run:
          command: |
            sudo apt-get install python3-pip
            pip3 install virtualenv --user 
            virtualenv -p python3 venv
      - run:
          command: |
            source venv/bin/activate
      - run:
          command: |
            pip install django
            pip3 install psycopg2       
      - run:
          command: |
            cd mysite
            python manage.py test
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1
      
