# Generated by Django 2.1.2 on 2018-11-13 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20181105_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daylog',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
    ]
